/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  darkMode: "class",
  theme: {
    extend: {
      textColor: {
        skin: {
          gray1: "var(--gray-1)",
          gray2: "var(--gray-2)",
          gray3: "var(--gray-3)",
          gray4: "var(--gray-4)",
          gray5: "var(--gray-5)",
          gray6: "var(--gray-6)",

          darkGray1: "var(--dark-gray-1)",
          darkGray2: "var(--dark-gray-2)",
          darkGray3: "var(--dark-gray-3)",
          darkGray4: "var(--dark-gray-4)",
          darkGray5: "var(--dark-gray-5)",
          darkGray6: "var(--dark-gray-6)",

          red: "var(--red)",
          orange: "var(--orange)",
          yellow: "var(--yellow)",
          green: "var(--green)",
          teal: "var(--teal)",
          cyan: "var(--cyan)",
          blue: "var(--blue)",
          indigo: "var(--indigo)",
          purple: "var(--purple)",
          pink: "var(--pink)",
          brown: "var(--brown)",

          darkRed: "var(--dark-red)",
          darkOrange: "var(--dark-orange)",
          darkYellow: "var(--dark-yellow)",
          darkGreen: "var(--dark-green)",
          darkTeal: "var(--dark-teal)",
          darkCyan: "var(--dark-cyan)",
          darkBlue: "var(--dark-blue)",
          darkIndigo: "var(--dark-indigo)",
          darkPurple: "var(--dark-purple)",
          darkPink: "var(--dark-pink)",
          darkBrown: "var(--dark-brown)",
        }
      },
      backgroundColor: {
        skin: {
          gray1: "var(--gray-1)",
          gray2: "var(--gray-2)",
          gray3: "var(--gray-3)",
          gray4: "var(--gray-4)",
          gray5: "var(--gray-5)",
          gray6: "var(--gray-6)",

          darkGray1: "var(--dark-gray-1)",
          darkGray2: "var(--dark-gray-2)",
          darkGray3: "var(--dark-gray-3)",
          darkGray4: "var(--dark-gray-4)",
          darkGray5: "var(--dark-gray-5)",
          darkGray6: "var(--dark-gray-6)",

          red: "var(--red)",
          orange: "var(--orange)",
          yellow: "var(--yellow)",
          green: "var(--green)",
          teal: "var(--teal)",
          cyan: "var(--cyan)",
          blue: "var(--blue)",
          indigo: "var(--indigo)",
          purple: "var(--purple)",
          pink: "var(--pink)",
          brown: "var(--brown)",

          darkRed: "var(--dark-red)",
          darkOrange: "var(--dark-orange)",
          darkYellow: "var(--dark-yellow)",
          darkGreen: "var(--dark-green)",
          darkTeal: "var(--dark-teal)",
          darkCyan: "var(--dark-cyan)",
          darkBlue: "var(--dark-blue)",
          darkIndigo: "var(--dark-indigo)",
          darkPurple: "var(--dark-purple)",
          darkPink: "var(--dark-pink)",
          darkBrown: "var(--dark-brown)",
        }
      },
    },
  },
  plugins: [
    require("@tailwindcss/typography"),
    require("tailwindcss-animate"),
  ],
};
