/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  theme: {
    extend: {
      animation: {
        "horizontal-bounce": "horizontal-bounce 0.8s ease-in-out infinite",
      },
      keyframes: {
        "horizontal-bounce": {
          "0%, 100%": {
            transform: "translateX(0)",
          },
          "50%": {
            transform: "translateX(2px)",
          },
        },
      },
      fontFamily: {
        mono: ["Geist Mono", "monospace"],
        sans: [
          "Geist Sans",
          "system-ui",
          "Segoe UI",
          "Roboto",
          "Helvetica",
          "Arial",
          "sans-serif",
          "Apple Color Emoji",
          "Segoe UI Emoji",
          "Segoe UI Symbol",
        ],
      },
      colors: {
        red: {
          1: "rgb(var(--red-1) / <alpha-value>)",
          2: "rgb(var(--red-2) / <alpha-value>)",
          3: "rgb(var(--red-3) / <alpha-value>)",
          4: "rgb(var(--red-4) / <alpha-value>)",
          5: "rgb(var(--red-5) / <alpha-value>)",
          6: "rgb(var(--red-6) / <alpha-value>)",
          7: "rgb(var(--red-7) / <alpha-value>)",
          8: "rgb(var(--red-8) / <alpha-value>)",
          9: "rgb(var(--red-9) / <alpha-value>)",
          10: "rgb(var(--red-10) / <alpha-value>)",
          11: "rgb(var(--red-11) / <alpha-value>)",
        },
        orange: {
          1: "rgb(var(--orange-1) / <alpha-value>)",
          2: "rgb(var(--orange-2) / <alpha-value>)",
          3: "rgb(var(--orange-3) / <alpha-value>)",
          4: "rgb(var(--orange-4) / <alpha-value>)",
          5: "rgb(var(--orange-5) / <alpha-value>)",
          6: "rgb(var(--orange-6) / <alpha-value>)",
          7: "rgb(var(--orange-7) / <alpha-value>)",
          8: "rgb(var(--orange-8) / <alpha-value>)",
          9: "rgb(var(--orange-9) / <alpha-value>)",
          10: "rgb(var(--orange-10) / <alpha-value>)",
          11: "rgb(var(--orange-11) / <alpha-value>)",
        },
        yellow: {
          1: "rgb(var(--yellow-1) / <alpha-value>)",
          2: "rgb(var(--yellow-2) / <alpha-value>)",
          3: "rgb(var(--yellow-3) / <alpha-value>)",
          4: "rgb(var(--yellow-4) / <alpha-value>)",
          5: "rgb(var(--yellow-5) / <alpha-value>)",
          6: "rgb(var(--yellow-6) / <alpha-value>)",
          7: "rgb(var(--yellow-7) / <alpha-value>)",
          8: "rgb(var(--yellow-8) / <alpha-value>)",
          9: "rgb(var(--yellow-9) / <alpha-value>)",
          10: "rgb(var(--yellow-10) / <alpha-value>)",
          11: "rgb(var(--yellow-11) / <alpha-value>)",
        },
        green: {
          1: "rgb(var(--green-1) / <alpha-value>)",
          2: "rgb(var(--green-2) / <alpha-value>)",
          3: "rgb(var(--green-3) / <alpha-value>)",
          4: "rgb(var(--green-4) / <alpha-value>)",
          5: "rgb(var(--green-5) / <alpha-value>)",
          6: "rgb(var(--green-6) / <alpha-value>)",
          7: "rgb(var(--green-7) / <alpha-value>)",
          8: "rgb(var(--green-8) / <alpha-value>)",
          9: "rgb(var(--green-9) / <alpha-value>)",
          10: "rgb(var(--green-10) / <alpha-value>)",
          11: "rgb(var(--green-11) / <alpha-value>)",
        },
        mint: {
          1: "rgb(var(--mint-1) / <alpha-value>)",
          2: "rgb(var(--mint-2) / <alpha-value>)",
          3: "rgb(var(--mint-3) / <alpha-value>)",
          4: "rgb(var(--mint-4) / <alpha-value>)",
          5: "rgb(var(--mint-5) / <alpha-value>)",
          6: "rgb(var(--mint-6) / <alpha-value>)",
          7: "rgb(var(--mint-7) / <alpha-value>)",
          8: "rgb(var(--mint-8) / <alpha-value>)",
          9: "rgb(var(--mint-9) / <alpha-value>)",
          10: "rgb(var(--mint-10) / <alpha-value>)",
          11: "rgb(var(--mint-11) / <alpha-value>)",
        },
        teal: {
          1: "rgb(var(--teal-1) / <alpha-value>)",
          2: "rgb(var(--teal-2) / <alpha-value>)",
          3: "rgb(var(--teal-3) / <alpha-value>)",
          4: "rgb(var(--teal-4) / <alpha-value>)",
          5: "rgb(var(--teal-5) / <alpha-value>)",
          6: "rgb(var(--teal-6) / <alpha-value>)",
          7: "rgb(var(--teal-7) / <alpha-value>)",
          8: "rgb(var(--teal-8) / <alpha-value>)",
          9: "rgb(var(--teal-9) / <alpha-value>)",
          10: "rgb(var(--teal-10) / <alpha-value>)",
          11: "rgb(var(--teal-11) / <alpha-value>)",
        },
        cyan: {
          1: "rgb(var(--cyan-1) / <alpha-value>)",
          2: "rgb(var(--cyan-2) / <alpha-value>)",
          3: "rgb(var(--cyan-3) / <alpha-value>)",
          4: "rgb(var(--cyan-4) / <alpha-value>)",
          5: "rgb(var(--cyan-5) / <alpha-value>)",
          6: "rgb(var(--cyan-6) / <alpha-value>)",
          7: "rgb(var(--cyan-7) / <alpha-value>)",
          8: "rgb(var(--cyan-8) / <alpha-value>)",
          9: "rgb(var(--cyan-9) / <alpha-value>)",
          10: "rgb(var(--cyan-10) / <alpha-value>)",
          11: "rgb(var(--cyan-11) / <alpha-value>)",
        },
        blue: {
          1: "rgb(var(--blue-1) / <alpha-value>)",
          2: "rgb(var(--blue-2) / <alpha-value>)",
          3: "rgb(var(--blue-3) / <alpha-value>)",
          4: "rgb(var(--blue-4) / <alpha-value>)",
          5: "rgb(var(--blue-5) / <alpha-value>)",
          6: "rgb(var(--blue-6) / <alpha-value>)",
          7: "rgb(var(--blue-7) / <alpha-value>)",
          8: "rgb(var(--blue-8) / <alpha-value>)",
          9: "rgb(var(--blue-9) / <alpha-value>)",
          10: "rgb(var(--blue-10) / <alpha-value>)",
          11: "rgb(var(--blue-11) / <alpha-value>)",
        },
        indigo: {
          1: "rgb(var(--indigo-1) / <alpha-value>)",
          2: "rgb(var(--indigo-2) / <alpha-value>)",
          3: "rgb(var(--indigo-3) / <alpha-value>)",
          4: "rgb(var(--indigo-4) / <alpha-value>)",
          5: "rgb(var(--indigo-5) / <alpha-value>)",
          6: "rgb(var(--indigo-6) / <alpha-value>)",
          7: "rgb(var(--indigo-7) / <alpha-value>)",
          8: "rgb(var(--indigo-8) / <alpha-value>)",
          9: "rgb(var(--indigo-9) / <alpha-value>)",
          10: "rgb(var(--indigo-10) / <alpha-value>)",
          11: "rgb(var(--indigo-11) / <alpha-value>)",
        },
        purple: {
          1: "rgb(var(--purple-1) / <alpha-value>)",
          2: "rgb(var(--purple-2) / <alpha-value>)",
          3: "rgb(var(--purple-3) / <alpha-value>)",
          4: "rgb(var(--purple-4) / <alpha-value>)",
          5: "rgb(var(--purple-5) / <alpha-value>)",
          6: "rgb(var(--purple-6) / <alpha-value>)",
          7: "rgb(var(--purple-7) / <alpha-value>)",
          8: "rgb(var(--purple-8) / <alpha-value>)",
          9: "rgb(var(--purple-9) / <alpha-value>)",
          10: "rgb(var(--purple-10) / <alpha-value>)",
          11: "rgb(var(--purple-11) / <alpha-value>)",
        },
        pink: {
          1: "rgb(var(--pink-1) / <alpha-value>)",
          2: "rgb(var(--pink-2) / <alpha-value>)",
          3: "rgb(var(--pink-3) / <alpha-value>)",
          4: "rgb(var(--pink-4) / <alpha-value>)",
          5: "rgb(var(--pink-5) / <alpha-value>)",
          6: "rgb(var(--pink-6) / <alpha-value>)",
          7: "rgb(var(--pink-7) / <alpha-value>)",
          8: "rgb(var(--pink-8) / <alpha-value>)",
          9: "rgb(var(--pink-9) / <alpha-value>)",
          10: "rgb(var(--pink-10) / <alpha-value>)",
          11: "rgb(var(--pink-11) / <alpha-value>)",
        },
        brown: {
          1: "rgb(var(--brown-1) / <alpha-value>)",
          2: "rgb(var(--brown-2) / <alpha-value>)",
          3: "rgb(var(--brown-3) / <alpha-value>)",
          4: "rgb(var(--brown-4) / <alpha-value>)",
          5: "rgb(var(--brown-5) / <alpha-value>)",
          6: "rgb(var(--brown-6) / <alpha-value>)",
          7: "rgb(var(--brown-7) / <alpha-value>)",
          8: "rgb(var(--brown-8) / <alpha-value>)",
          9: "rgb(var(--brown-9) / <alpha-value>)",
          10: "rgb(var(--brown-10) / <alpha-value>)",
          11: "rgb(var(--brown-11) / <alpha-value>)",
        },
        gray: {
          1: "rgb(var(--gray-1) / <alpha-value>)",
          2: "rgb(var(--gray-2) / <alpha-value>)",
          3: "rgb(var(--gray-3) / <alpha-value>)",
          4: "rgb(var(--gray-4) / <alpha-value>)",
          5: "rgb(var(--gray-5) / <alpha-value>)",
          6: "rgb(var(--gray-6) / <alpha-value>)",
          7: "rgb(var(--gray-7) / <alpha-value>)",
          8: "rgb(var(--gray-8) / <alpha-value>)",
          9: "rgb(var(--gray-9) / <alpha-value>)",
          10: "rgb(var(--gray-10) / <alpha-value>)",
          11: "rgb(var(--gray-11) / <alpha-value>)",
        },
        backdrop: "rgb(var(--backdrop) / <alpha-value>)",
        background: "rgb(var(--background) / <alpha-value>)",
        backgroundVariant: "rgb(var(--background-variant) / <alpha-value>)",
        text: "rgb(var(--text) / <alpha-value>)",
        textVariant: "rgb(var(--text-variant) / <alpha-value>)",
        primary: "rgb(var(--primary) / <alpha-value>)",
        primaryVariant: "rgb(var(--primary-variant) / <alpha-value>)",
        secondary: "rgb(var(--secondary) / <alpha-value>)",
        secondaryVariant: "rgb(var(--secondary-variant) / <alpha-value>)",
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
  corePlugins: {
    preflight: false,
  },
  darkMode: "class",
};
